package com.yelo.app.entity;
// Generated Nov 5, 2020 12:04:50 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Car generated by hbm2java
 */
@Entity(name = "car")
public class Car implements java.io.Serializable {

    private Long id;
    private String owner;
    private String name;
    private String color;
    private String model;
    
    private byte hideMe;

    public Car() {
    }

    public Car(String owner, String name, String color, String model, byte hideMe) {
        this.owner = owner;
        this.name = name;
        this.color = color;
        this.model = model;
        this.hideMe = hideMe;
    }

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @JoinColumn(name = "owner", nullable = false)
    public String getOwner() {
        return this.owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    @Column(name = "name", nullable = false)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "color", nullable = false, length = 200)
    public String getColor() {
        return this.color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    @Column(name = "model", nullable = false, length = 50)
    public String getModel() {
        return this.model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    @Column(name = "hide_me", nullable = false)
    public byte getHideMe() {
        return this.hideMe;
    }

    public void setHideMe(byte hideMe) {
        this.hideMe = hideMe;
    }

}
